language: clojure
lein: lein
branches:
  only:
    - master
jdk:
  - oraclejdk8
  - oraclejdk9
notifications:
  email:
    - ertu.ctn@gmail.com

after_success:
- CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
